### ISSUE TITLE
Add mobile element calling into the pipeline

### ISSUE THREAD

**Issue by peterpru** [Clinical-Genomics/raredisease#12]
### Description of feature

From talking to clinicians: As a clinician, I need the pipeline to be able pinpoint mobile element insertions in our genomic data for detecting disease-causing variants.

Link to nf-core issue: https://github.com/nf-core/raredisease/issues/329

Current suggested solution: Add a retroseq subworkflow as implemented in MIP.

Actions:
- [x] Add retroseq discover as local module
- [x] Add retroseq call as local module
- [x] Add call subworkflow
- [x] Add annotation subworkflow

PR for nf-core: 
https://github.com/nf-core/raredisease/pull/440
https://github.com/nf-core/raredisease/pull/483

**Comment by jemten** [comment]
done in dev branch and awaiting new release
