### ISSUE TITLE
ExHu/Stranger VCF unsplit

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/raredisease#15]
### Description of the bug

The ExHu/Stranger VCF delivered appears to be an unnormalised/unsplit version:

```
4       3076603 .       C       <STR17>,<STR24> .       PASS    END=3076660;....
```

**Comment by jemten** [comment]
Hmm, we have a normalisation step in that subworkflow but it is obviously something wrong in the implementation of it. Will look into it
