### ISSUE TITLE
Overzealous html escapes in VCF?

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/raredisease#20]
### Description of the bug

See https://github.com/Clinical-Genomics/scout/issues/4397 and https://github.com/Clinical-Genomics/scout/pull/4577. In particular we identify the DOMAINS field of the INFO.CSQ, which should have entries separated by `&` where each entry is a tuple `TYPE:ID` separated by `:`. The `:` get escaped to `%3A` though, which make them harder to read and parse.

**Comment by jemten** [comment]
fixed with https://github.com/nf-core/raredisease/pull/538
